### ISSUE TITLE
Status updates need to check for permissions

### ISSUE THREAD

**Issue by zoidbergwill** [markstory/lint-review#112]
This stopped the comment from happening, we should either fail more gracefully or raise an appropriate error. Not sure when the right time to raise the error is though.

A bot with a read-only token can comment and do the rest of the things it seems, but not update the status: https://developer.github.com/v3/repos/statuses/#create-a-status

```
[2016-07-25 13:36:49,304: INFO/Worker-8] Building a url from ('https://api.github.com/repos/Superbalist/XXXXXX', 'statuses', '08330c85fd6ee16508f2d00f42b1406e519f4916')
[2016-07-25 13:36:49,419: INFO/Worker-8] JSON was not returned
```

**Comment by markstory** [comment]
Were you hoping for an error log?

**Comment by zoidbergwill** [comment]
Yeah, I think if we just catch it and add a proper error message that'd be okay. I'll take a look tomorrow morning.

**Comment by markstory** [comment]
ping.

**Comment by markstory** [comment]
Closing as folks should configure their bot accounts with the correct permissions and this doesn't seem to be a common enough issue that I want to spend time fixing it.
