### ISSUE TITLE
Linting fails if there's no reviewable changes

### ISSUE THREAD

**Issue by adrianmoisey** [markstory/lint-review#114]
https://github.com/markstory/lint-review/blob/98488db50f629090969ca67254f2a102f8516e8e/lintreview/review.py#L231-L243

That sends an error status to the github api. I made a valid PR that just deleted code, but the bot made my build fail.

Would it make sense to switch this to "success" ? I'm not 100% sure if that's right either.

**Comment by markstory** [comment]
If the diff is to big error makes sense, if its too small then success makes sense. I don't think we can easily separate those two states from the diff API though.

**Comment by adrianmoisey** [comment]
:)
