### ISSUE TITLE
Public repository in Github enterprise cannot clone.

### ISSUE THREAD

**Issue by aha-oretama** [markstory/lint-review#128]
Inputing user name and Oath token or password is necessary to clone public repository in GhE.
But the process of cloning public repository in GhE is not in [git.py#L75](https://github.com/markstory/lint-review/blob/master/lintreview/git.py#L77) but in [git.py#L75](https://github.com/markstory/lint-review/blob/master/lintreview/git.py#L75).

So that, the worker process stops in the process of cloning.
The process of cloning public repository in GhE must be like private_clone.

**Comment by aha-oretama** [comment]
It is possible to avoid above problem by writing following text in `~/.netrc`.

```
machine github-hostname
login username
password password-or-oathToken
```

But it is just work-around.
It is desired to solve the problem

**Comment by markstory** [comment]
>  The process of cloning public repository in GhE must be like private_clone.

That has not been my experience. I use a very recent version of lint-review with my work's github:e instance and the current cloning code for public projects works fine. Perhaps there are configuration differences between the github:e that I use and yours though.

**Comment by aha-oretama** [comment]
Oh... I think that the following setting occurs the problem.
https://help.github.com/enterprise/2.9/admin/guides/installation/enabling-private-mode/

Thank you for your answer.
It is impossible to know the configuration in github enterpirse in worker process.
Therefore, there is no solution in source code for this problem.

But I think that this issue will be a knowledge!
That's OK. Please close this issue.

**Comment by markstory** [comment]
Thanks for finding that @aha-oretama. It should be helpful for the next person who runs into this issue.
