### ISSUE TITLE
Support for Swift

### ISSUE THREAD

**Issue by aha-oretama** [markstory/lint-review#139]
Do you have any plans to support for Swift such as [SwiftLint](https://github.com/realm/SwiftLint)?

**Comment by markstory** [comment]
Yes. The challenge with most iOS tools has been getting them working on Linux which is necessary for testing.

**Comment by aha-oretama** [comment]
Oh, nice! I'm looking forward to seeing the support for Swift!

**Comment by markstory** [comment]
Do you want to help? The linter tools are usually simple if the tool outputs a machine readable format.

**Comment by markstory** [comment]
Pull request open now. I've not addressed getting swiftlint running in docker as that is a hot mess right now.

**Comment by aha-oretama** [comment]
Thank you!
