### ISSUE TITLE
js files are being linted with both eslint and jshint

### ISSUE THREAD

**Issue by fr33l** [markstory/lint-review#161]
We recently implemented eslint into some of our projects and we want these projects to be linted only with eslint. `.lintrc` files were updated there, jshint was replaced with eslint, however,  jshint still reviews those projects and posts reviews along with eslint, is there some misconfiguration on our side or we have to get rid from jshint entirely?  
Any reply is much appreciated.

**Comment by markstory** [comment]
Do you have jshint enabled in the default linters by chance?

**Comment by fr33l** [comment]
LINTRC_DEFAULTS  here?

**Comment by markstory** [comment]
Yes. If `LINTRC_DEFAULTS` enables jshint, it will be applied to all projects your lintreview runs on.

**Comment by fr33l** [comment]
we only have `tool_`  prefixed  sections there for tools, config file for jshint is there, but there is no `[tools]` section

**Comment by fr33l** [comment]
Actually removing `[tool_jshint]`  section helped, jshint doesn't run now on  projects where  it's not specified in `.lintrc`. But this means that we have to set config path in each project individually. 
Is this expected behaviour?

**Comment by markstory** [comment]
> But this means that we have to set config path in each project individually.
Is this expected behaviour?

Yes. Each project will need to configure the tools it uses.

**Comment by markstory** [comment]
Closing as this was a configuration issue.

**Comment by fr33l** [comment]
Thanks for quick response
