### ISSUE TITLE
Option to delete checkout when done

### ISSUE THREAD

**Issue by KeithScheiwiller** [markstory/lint-review#165]
It would be very beneficial to have an option to delete the checkedout repo after the review is finished.
Our repos are on the rather large size, and the disk is filling up very fast due to all the checkouts.
I still think it's beneficial to start clean each time, it would just be nice to be able to clean up afterwards.

**Comment by markstory** [comment]
Repositories should be deleted when the pull requests are closed/merged. Instead of an option deleting the repositories after review could be the new default. I'm not sure having more knobs is required here.
