### ISSUE TITLE
shellcheck on stickler-ci doesn't understand the source directive

### ISSUE THREAD

**Issue by cailyoung** [markstory/lint-review#172]
To reproduce:

`#! /bin/bash`
`# shellcheck source=scripts/inc/librelease.sh disable=SC1091`
`source "${SCRIPT_HOME}/inc/librelease.sh"`

Live example:
https://github.com/CommandPost/CommandPost/pull/929#pullrequestreview-86128820

When pasted in shellcheck.net no issues are found.

Perhaps it is running an older build of shellcheck?

**Comment by markstory** [comment]
I'll look into getting shellcheck updated. The installed version may be a few months old now.

**Comment by markstory** [comment]
Shellcheck has been updated to 0.4.7 now.
