### ISSUE TITLE
Build GitHub  Tags

### ISSUE THREAD

**Issue by zoidbergwill** [markstory/lint-review#173]
It'd be awesome to have versioned Docker images because at the moment the only real version is `latest`/`master`.

**Comment by markstory** [comment]
I could update my release process to create tagged images going forward, I doubt I'll find time to make historical tags though.

**Comment by zoidbergwill** [comment]
Just doing going forward with PyPI releases would be awesome.

**Comment by markstory** [comment]
Should be good now. I've updated dockerhub configuration to start building each tag.
