### ISSUE TITLE
Support for multiple language versions

### ISSUE THREAD

**Issue by alzabo** [markstory/lint-review#178]
I'm running lint-review for several projects tracked on a GitHub Enterprise instance, and it's working great for us, but one of the engineering teams I support maintains mixed Python 2.7 and 3.x apps.

I'm comfortable with hacking something up for us to use internally, but wanted to see if you have a preference for implementation in case you'd consider a PR; if nothing else, contributing my changes upstream means less work maintaining my fork.

In terms of implementation, the choices seem to be:

1. Add config option for command path

This could be done one of two ways -- either a configurable command name (absolute path, prefixed/suffixed) or an option to push directories onto $PATH

  This change would be relatively straightforward to implement with a config like:

  ```
  [tools]
  linters = flake8

  [tool_flake8]
  select = E702
  executable = flake8-3.5
  ```

2. Add more tools
  This doesn't seem like a very good approach as it would entail adding a dozen tools. Even if they were sub-classes of the "main" tool of a given type, all the added code (including tests) would be a chore to maintain

3. Some other clever thing
My idea here would be something along the lines of adding a new config element amounting to a mapping of interpreter name to a command to "activate" it when the Processor class is initialized.

```python
INTERPRETERS = {
    'python-3.5': '/opt/python/3.5/bin/activate',
    'ruby-2.2': "export PATH='/opt/ruby/2.2/bin:$PATH'", }
```

This would probably end up being buggy and unpredictable, and in fact, seems like the worst solution now that I write it out.

---
If this is something you'd consider accepting a PR for, I'd think option 1 would be the way to go, unless you have another suggestion

**Comment by markstory** [comment]
I suspect this is only an issue with python tools, as other languages don't have the parser incompatiblities that python 2 & 3 have.

Have you considered a more abstract configuration option for use in the ini file? Perhaps something like `python=3`? The specific paths can then be an mapping inside of lintreview. This would allow repositories reviewed by lintreview to be insulated from specific paths that only exist outside the repository.

Adding more tools is an option, but it does suffer from the drawbacks you raised.

**Comment by alzabo** [comment]
FWIW my use case is solved by the dockerized tools and python3 container
