### ISSUE TITLE
flake8 exclude doesn't work as expected for directories

### ISSUE THREAD

**Issue by shoyer** [markstory/lint-review#184]
With flake8 alone, if I try to exclude my documentation directory as follows, it works:
```
flake8 --exclude=doc/ .
```

However, Stickler-CI includes [each file explicitly](https://github.com/markstory/lint-review/blob/2b6d29a76f68efeaca543d9c830fb5558366bd6a/lintreview/tools/flake8.py#L69) in the command line invocation, e.g.,
```
flake8 --exclude=doc/ doc/examples/_code/weather_data_setup.py
```

With this version, the explicitly listed file is no longer included. Instead, I spent a while being frustrated (thinking I was misusing flake8) and eventually found Stickler's `files.ignore` option.

It might be worth noting this in the docs somewhere. There appears to already be a bug report upstream for flake8: https://gitlab.com/pycqa/flake8/issues/392

**Comment by markstory** [comment]
I'm not clear on what changes you're wanting to see made to the documentation? Is it that the `exclude` option doesn't work on directories?

**Comment by shoyer** [comment]
>  Is it that the exclude option doesn't work on directories?

Yes, that's right. You need to specify full filenames (or use `ignore.files`).

**Comment by markstory** [comment]
Ok. I can do that.

**Comment by markstory** [comment]
Docs are updated in both this project and on stickler-ci.com.

**Comment by shoyer** [comment]
Thanks!
