### ISSUE TITLE
Installing GitHub hooks via Docker after settings configuration doesn't work

### ISSUE THREAD

**Issue by tedmdelacruz** [markstory/lint-review#193]
Following the instructions for setting up webhooks I ran into a problem.

After configuring `GITHUB_OAUTH_TOKEN` token and other fields in `settings.py` in [Lint Review Configuration](https://github.com/markstory/lint-review#lint-review-configuration) I tried installing webhooks as per [Installing GitHub hooks](https://github.com/markstory/lint-review#installing-github-hooks) but I got a `Bad credentials` error.

Checking the `settings.py` in the `web` container, it seems untouched. The `GITHUB_OAUTH_TOKEN` and other fields were still in their respective default values.

Restarting the container with `docker-compose restart web` still doesn't reflect the changes.

Please advise, thanks!

**Comment by tedmdelacruz** [comment]
#194 Fixed this on my end

**Comment by markstory** [comment]
Pull request open now.
