### ISSUE TITLE
Source file not found

### ISSUE THREAD

**Issue by victorvianna** [markstory/lint-review#216]
I was testing the code by trying to verify some simple pull requests. (I'm running through docker.) However when I open a pull request, I get the following error:
```
E902 IOError: [Errno 2] No such file or directory: '/src/foo.py'
```

**Comment by markstory** [comment]
Sounds like the worker's linting container doesn't have the application code mounted in.

**Comment by victorvianna** [comment]
Even when I run without docker, it just hangs and doesn't post any comments to the pull request.
```
Some checks haven’t completed yet
```

**Comment by markstory** [comment]
Have you build the docker images that contain the required linting tools? Where does it hang if you enable debug logging?

**Comment by victorvianna** [comment]
[INFO] Listening at: http://127.0.0.1:5001 (23453)
[INFO] Using worker: sync
[INFO] Booting worker with pid: 23457

**Comment by victorvianna** [comment]
For docker, I've also tried to go back to the commit "Fix anchor" and build the images myself, but he won't even find npm package with apt-get :/

**Comment by markstory** [comment]
So are you not able to build the images for lintreview? or the linter images (as they are separate).

**Comment by victorvianna** [comment]
For the non-docker version, I tried to make a request to  the '/ping' route and the problem appears to be gunicorn. The logs detect the request, but the response is 404.

**Comment by victorvianna** [comment]
## Docker

Just tried commits 972024fe32c20dc1d3cae128cbdc28109c5d948d and 7249da041306f0bb01e4becd17541deb2295d6d0 locally (manjaro 17.10) and I get the same thing for both, namely:
1) 'web' is classified as unhealthy when running "docker-compose ps" (no proper ping response)
2) I see no src folder when running  
```
docker-compose run web /bin/bash
ls /src
```
Number 2 may make no sense, cuz' I don't know much docker yet. I've also tried 2 with 'worker' instead of 'web'.

**Comment by markstory** [comment]
@victorvianna Neither the web or consumer containers will have a `/src` directory. This directory only exists in the linter containers. The consumer spins up additional docker container for each linting tool that is run. Linters are run in separate containers as many of them execute code in the repository.

**Comment by victorvianna** [comment]
When replacing PEP8 by Flake8, it won't display the '/src/' problem anymore, except that it won't show any corrections. 
[Pull request example](https://github.com/victorvianna/webhooks/pull/10)
[Code I'm running](https://github.com/victorvianna/lint-review/commit/c1f846212facffe6f2f534d15945b327fa899c14)
Log output
```
worker_1  | [2018-08-13 15:09:39,857: INFO/Worker-1] Starting to process lint for victorvianna/webhooks/10
worker_1  | [2018-08-13 15:09:39,859: INFO/Worker-1] Loading pull request data from github. user=victorvianna repo=webhooks number=10
worker_1  | [2018-08-13 15:09:39,864: INFO/Worker-1] Building a url from ('https://api.github.com', 'repos', 'victorvianna', 'webhooks')
worker_1  | [2018-08-13 15:09:39,864: INFO/Worker-1] Missed the cache building the url
worker_1  | [2018-08-13 15:09:39,964: INFO/Worker-1] Attempting to get JSON information from a Response with status code 200 expecting 200
worker_1  | [2018-08-13 15:09:39,965: INFO/Worker-1] JSON was returned
worker_1  | [2018-08-13 15:09:39,969: INFO/Worker-1] Building a url from ('https://api.github.com/repos/victorvianna/webhooks', 'pulls', '10')
worker_1  | [2018-08-13 15:09:39,969: INFO/Worker-1] Missed the cache building the url
worker_1  | [2018-08-13 15:09:40,122: INFO/Worker-1] Attempting to get JSON information from a Response with status code 200 expecting 200
worker_1  | [2018-08-13 15:09:40,123: INFO/Worker-1] JSON was returned
worker_1  | [2018-08-13 15:09:40,125: INFO/Worker-1] Missed the cache building the url
worker_1  | [2018-08-13 15:09:40,246: INFO/Worker-1] Attempting to get JSON information from a Response with status code 201 expecting 201
worker_1  | [2018-08-13 15:09:40,246: INFO/Worker-1] JSON was returned
worker_1  | [2018-08-13 15:09:40,248: INFO/Worker-1] Cloning repository 'https://github.com/victorvianna/webhooks.git' into '/tmp/workspace/victorvianna/webhooks/10'
worker_1  | [2018-08-13 15:09:40,594: INFO/Worker-1] Checking out '478e862f696148ee26e0d17b26b91862178ddafe'
worker_1  | [2018-08-13 15:09:40,600: INFO/Worker-1] Loading pull request patches from github.
worker_1  | [2018-08-13 15:09:40,600: INFO/Worker-1] Building a url from ('https://api.github.com/repos/victorvianna/webhooks/pulls/10', 'files')
worker_1  | [2018-08-13 15:09:40,600: INFO/Worker-1] Missed the cache building the url
worker_1  | [2018-08-13 15:09:40,674: INFO/Worker-1] Attempting to get JSON information from a Response with status code 200 expecting 200
worker_1  | [2018-08-13 15:09:40,675: INFO/Worker-1] JSON was returned
worker_1  | [2018-08-13 15:09:40,676: INFO/Worker-1] Building a url from ('https://api.github.com/repos/victorvianna/webhooks/pulls/10', 'commits')
worker_1  | [2018-08-13 15:09:40,677: INFO/Worker-1] Missed the cache building the url
worker_1  | [2018-08-13 15:09:40,678: INFO/Worker-1] Running lint tools on 1 files
worker_1  | [2018-08-13 15:09:40,679: INFO/Worker-1] Running flake8 on 1 files
worker_1  | [2018-08-13 15:09:40,679: INFO/Worker-1] Running python2 container
worker_1  | [2018-08-13 15:09:41,766: INFO/Worker-1] Building a url from ('https://api.github.com/repos/victorvianna/webhooks/pulls/10', 'comments')
worker_1  | [2018-08-13 15:09:41,766: INFO/Worker-1] Missed the cache building the url
worker_1  | [2018-08-13 15:09:41,826: INFO/Worker-1] Attempting to get JSON information from a Response with status code 200 expecting 200
worker_1  | [2018-08-13 15:09:41,826: INFO/Worker-1] JSON was returned
worker_1  | [2018-08-13 15:09:41,826: INFO/Worker-1] Publishing review of 0 new comments for victorvianna/webhooks/pull/10
worker_1  | [2018-08-13 15:09:41,826: INFO/Worker-1] Building a url from ('https://api.github.com/repos/victorvianna/webhooks', 'statuses', '478e862f696148ee26e0d17b26b91862178ddafe')
worker_1  | [2018-08-13 15:09:41,956: INFO/Worker-1] Attempting to get JSON information from a Response with status code 201 expecting 201
worker_1  | [2018-08-13 15:09:41,957: INFO/Worker-1] JSON was returned
worker_1  | [2018-08-13 15:09:41,958: INFO/Worker-1] Completed lint processing for victorvianna/webhooks/10
worker_1  | [2018-08-13 15:09:41,963: INFO/Worker-1] Cleaned up pull request victorvianna/webhooks/10
worker_1  | [2018-08-13 15:09:41,966: INFO/MainProcess] Task lintreview.tasks.process_pull_request[7c147c1d-6959-49a4-9b12-904298d35aa3] succeeded in 2.10858612496s: None

```

**Comment by markstory** [comment]
> worker_1  | [2018-08-13 15:09:41,826: INFO/Worker-1] Publishing review of 0 new comments for victorvianna/webhooks/pull/10

Is the key line here. Are you certain that your pull request contains lines that would trigger flake8 errors? lintreview only looks at lines that were changed in the pull request. If you set the logging level to DEBUG you'll get more output from the linter output and which errors survived filtering.

**Comment by victorvianna** [comment]
>Are you certain that your pull request contains lines that would trigger flake8 errors?

Yes. If I run the python2 container directly from my machine, the linter works, for example as in
```
echo "  x== 2 " > /tmp/foo.py
docker run --rm -v /tmp:/src flake8 --isolated /src/foo.py
#linter works
```
But it won't work if a container tries to run it The problem appears to be with the binding and is independent of the image you use. Ex:
```
user@pc:lint-review $ docker-compose run -it worker /bin/bash
root@worker:/code # 
root@worker:/code # touch /tmp/A.txt
root@worker:/code # docker run -it -v /tmp:/src some_image /bin/bash
root@some_image:/src#
root@some_image:/src# ls
# Won't show file A.txt
```

**Comment by victorvianna** [comment]
I think if we declare a named volume in the base container, mount it as /tmp in the worker and then /src in the linters, it will work.

**Comment by markstory** [comment]
@kostiq I don't know how to reproduce it so its stalled.

**Comment by markstory** [comment]
Ok. You're likely going to have to debug this on your own as reviews worked locally for me last time I tried (earlier in this thread).

The consumer first clones your repository with
```
[2018-10-11 07:09:17,329: DEBUG/Worker-1] Running ['git', 'clone', u'...github.com/kostiq/task.git', u'/tmp/workspace/kostiq/task/13']
```

It then runs the following docker command:

```
[2018-10-11 07:09:18,490: DEBUG/Worker-1] Running ['docker', 'run', '--rm', '-v', u'/tmp/workspace/kostiq/task/13:/src', 'python3', 'pep8', '-r', '/src/union_lists.py']
```

Are you able to run those commands inside the consumer container to see if you can reproduce the missing/bad volume mount?

**Comment by kostiq** [comment]
Yeah.
In consumer I run following commands:

`git clone`
<img width="1092" alt="screenshot 2018-10-11 at 17 38 51" src="https://user-images.githubusercontent.com/8676640/46812316-24fd8280-cd7d-11e8-8f7d-2b14d7e21131.png">

check files
<img width="441" alt="screenshot 2018-10-11 at 17 39 08" src="https://user-images.githubusercontent.com/8676640/46812348-38105280-cd7d-11e8-89cd-2fb5083c1a36.png">

And `docker run` with volumes
<img width="825" alt="screenshot 2018-10-11 at 17 39 22" src="https://user-images.githubusercontent.com/8676640/46812385-48283200-cd7d-11e8-9f38-20826ccdaf02.png">

**Comment by markstory** [comment]
Ok. So until you can fix that lintreview will not work correctly. It seems like the volume mount from the consumer into the tool container is not working correctly.

**Comment by kostiq** [comment]
Ok. I will try.
