### ISSUE TITLE
Unable to connect Sticker CI to an organization repo

### ISSUE THREAD

**Issue by sargunv** [markstory/lint-review#220]
I've attached a screenshot of the error message. In Github, the application was linked to the org and repo, but Stickler doesn't see it. This happens for both "All repositories" and for "Only select repositories".

![capture](https://user-images.githubusercontent.com/1320357/45252021-2ca4b400-b305-11e8-8d03-8340f5026ac1.PNG)

**Comment by sargunv** [comment]
I wasn't sure if this or email was the right option for reporting a Sticker CI issue, so I did both 😀

**Comment by markstory** [comment]
@sargunv The problem you were having should be fixed now. Let me know if you run into any other problems.

**Comment by sargunv** [comment]
It works, thanks!
