### ISSUE TITLE
Use the flake8 config file

### ISSUE THREAD

**Issue by sargunv** [markstory/lint-review#221]
The current flake module takes config options and passes them to flake by CLI params. Would it be possible to support a flake config file instead, so I don't have to duplicate my flake config across tox.ini and .stickler.yml?

The black, eslint, etc modules already do this.

**Comment by markstory** [comment]
Yes. You can use the `config` option with `flake8` to specify the config file for your project. This option is missing from the documentation, but will be added shortly.

**Comment by sargunv** [comment]
I tried with `config: ./tox.ini` and it didn't work, flake8 applied lint rules that were in my `ignore` config. A manual local run of flake8 read the config fine.

**Comment by markstory** [comment]
How were you running flake8 locally? We use the `--isolated --config` options. We have to use isolated mode as project config file can change the output mode into a non-parsable format.

**Comment by sargunv** [comment]
I did some local tests with these flags:

 - `flake8`: detects the config and runs as expected
 - `flake8 --config tox.ini`: uses the provided config and runs as expected
 - `flake8 --config tox.ini --isolated` ignored the provided config and runs with default options, causing problems

According to `flake8 --help`, looks like `--config` already ignores configs other than the one provided, so `--isolated` is redundant (and seems to be clobbering `--config`). 

```
  --config=CONFIG       Path to the config file that will be the authoritative
                        config source. This will cause Flake8 to ignore all
                        other configuration files.
  --isolated            Ignore all found configuration files.
```

**Comment by sargunv** [comment]
Yep, just checked out the flake8 source and seems like you should be calling flake8 with just `--config`, since `--isolated` will ignore *all* configs, not just found ones. 

https://github.com/PyCQA/flake8/blob/master/src/flake8/options/config.py#L277
