### ISSUE TITLE
Add support for kotlin lint

### ISSUE THREAD

**Issue by fadeltd** [markstory/lint-review#248]
Hello, I've just come across this repository, and I'm really interested, can you add lint for **kotlin**? I've read that this project already support swiftlint that's been widely used for ios development, so would it be possible to also support kotlin for android development? There's also already a very good kotlin linter like [**ktlint**](https://github.com/shyiko/ktlint)

I've checked that ktlint also support checkstyle xml output, and fix.

Thanks

**Comment by markstory** [comment]
Closing this issue as there is a pull request open now. :+1:
