### ISSUE TITLE
Add json linting

### ISSUE THREAD

**Issue by adrianmoisey** [markstory/lint-review#50]
It would be really nice if lint-review could lint .json files. Possibly with https://www.npmjs.com/package/jsonlint

**Comment by markstory** [comment]
Sounds like a good idea to me.

**Comment by adrianmoisey** [comment]
This seems to be a good option: https://www.npmjs.com/package/jsonlint

**Comment by adrianmoisey** [comment]
Oh, all it does it print out a cleaner copy of the json. That won't work.
