### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by adrianmoisey** [markstory/lint-review#58]
Because https://github.com/markstory/lint-review/pull/57 and https://github.com/markstory/lint-review/pull/55 and https://github.com/markstory/lint-review/pull/53 have all landed, what about bumping the version?

**Comment by markstory** [comment]
I can do that tonight.

**Comment by adrianmoisey** [comment]
:+1:

**Comment by markstory** [comment]
0.0.16 tagged now.
